### PR TITLE
Fix atoum command exit codes

### LINKED ISSUE #97: Bad exit value for the command
The command always end with a 0 exit code, even if the tests failed.
Is it possible to have it return an error code if necessary, as using atoum directly I would guess?

### PR DESCRIPTION
**Pull request by jubianchi**
Closes #97 

@maxailloud this should fix your issue. Would you have some time to test this branch and confirm it's OK ?

Thanks.

### CODE REVIEW

File: Command/AtoumCommand.php [hunk 1]
```diff
@@ -121,7 +121,27 @@ protected function execute(InputInterface $input, OutputInterface $output)
             $reportCli->addWriter($writerCli);
         }
 
-        $runner->run($this->getAtoumArguments());
+        try {
+            $score = $runner->run()->getRunner()->getScore();
```
Comment (maxailloud) [inline Command/AtoumCommand.php]: I think you forgot to add the parameter `$this->getAtoumArguments()`to the run method because without it it's not working.
Without this parameters I have the message ``Error: Unable to add test file 'atoum'`.
But except that it's working nicely, good job man.

Comment (jubianchi) [inline Command/AtoumCommand.php]: Let me fix it! Thanks for you feedback.

I'll update the PR, merge it and issue a new release ;)

**Comment by maxailloud** [comment]
Thanks man.
Do you know when will you do a new release with that commit?

**Comment by jubianchi** [comment]
@maxailloud in less than one hour ;)

**Comment by maxailloud** [comment]
Sweet, thanks.
